#!/bin/bash
##########################
# New Playlists

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV House [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV House [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlAMTvakabnwTNc00cD_S6v"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Requests and Meme [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Requests and Meme [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzmQUw-lfGxbjhMcRFqVkrNq"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Progressive [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Progressive [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlrSNdvG-kDaM2Vaq_6g8Zq"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Techno [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Soiler Womb IV Techno [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzkmulluN2td4YojViRa4CJE"

######################
# Other Playlists

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Youtube Exclusive'
cd '/Users/garges/Desktop/SOILERWOMBIV/Youtube Exclusive'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlYVRf0mrU8eIhpKCzvy-Sf"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Call on Me Stolen'
cd '/Users/garges/Desktop/SOILERWOMBIV/Call on Me Stolen'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlznvgOQ7pLCmorLZfs5AQKgV"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Mar vista #2 [Wil]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Mar vista #2 [Wil]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL6s5g3imt6RD_kZg1JcJp5Y3tfTOGE8Th"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/ELECTRO español [Hannah]'
cd '/Users/garges/Desktop/SOILERWOMBIV/ELECTRO español [Hannah]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PLYF002ywZd7YkgrG-wlq-f5veAwG3rnZG"

##########################
# Backup Playlists

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Techno Dump [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Techno Dump [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzkjSSw8ATXcAM3-WFg_elqu"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Meme [Compliation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Meme [Compliation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlznOl5I-Sqyc6BloMS724KF3"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Soft Cave Vibes [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Soft Cave Vibes [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzkp9bll4SSf19-_XuV5fSQi"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/NEW (House   Disco) [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/NEW (House   Disco) [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlo0VKqmm3qVlgSvZAuwUhT"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Transition [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Transition [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlYPEuF4vV4dVSxm-VFpQJP"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/90s Rave [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/90s Rave [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzmZB_3eJTWyCllGIMqaOfcn"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Daft Punk / FN / FT [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Daft Punk / FN / FT [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlcuoY8Koy7g-8WFfKNct9S"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Cave Rave 2.0 [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Cave Rave 2.0 [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzmUV6g4J7VIeM02cLIIjWdj"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/This is my mix [Compilation]'
cd '/Users/garges/Desktop/SOILERWOMBIV/This is my mix [Compilation]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlAfD9f3jgR4Zf-nQTGiadE"

######################

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Youtube Exclusive'
cd '/Users/garges/Desktop/SOILERWOMBIV/Youtube Exclusive'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlzlYVRf0mrU8eIhpKCzvy-Sf"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Call on Me Stolen'
cd '/Users/garges/Desktop/SOILERWOMBIV/Call on Me Stolen'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL9PJOAjeIlznvgOQ7pLCmorLZfs5AQKgV"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/Mar vista #2 [Wil]'
cd '/Users/garges/Desktop/SOILERWOMBIV/Mar vista #2 [Wil]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PL6s5g3imt6RD_kZg1JcJp5Y3tfTOGE8Th"

sleep 2
mkdir '/Users/garges/Desktop/SOILERWOMBIV/ELECTRO español [Hannah]'
cd '/Users/garges/Desktop/SOILERWOMBIV/ELECTRO español [Hannah]'
/usr/local/bin/python3 /usr/local/bin/youtube-dl --extract-audio --rm-cache-dir --audio-format mp3 --download-archive archive.txt "https://www.youtube.com/playlist?list=PLYF002ywZd7YkgrG-wlq-f5veAwG3rnZG"


# My Youtube Playlist URLs:
# Soiler Womb IV Techno [Compilation]
# https://www.youtube.com/playlist?list=PL9PJOAjeIlzkhWLNDEAOY-YSuCrJ4aEoK
#
#
#
#
#
#
#
#
#
#
#
# Playlist URLs from Colaborators:
#
#
#
